- hosts: your_vm_public_ip
  become: yes
  tasks:
    - name: Clone your repository
      git:
        repo: https://github.com/yourusername/your-repo.git
        dest: /home/azureuser/your-repo
        force: yes

    - name: Install Node.js
      become: yes
      apt:
        name: nodejs
        state: present

    - name: Install npm
      become: yes
      apt:
        name: npm
        state: present

    - name: Change directory to your repository
      become: yes
      shell: cd /home/azureuser/your-repo

    - name: Install project dependencies
      become: yes
      shell: npm install

    - name: Start the NestJS application
      become: yes
      command: npm start
      args:
        chdir: /home/azureuser/your-repo
